### ISSUE TITLE
你好，我的QQ：251808309，方便加一下，沟通下iOS上的pzip问题吗？有重谢！！！

### ISSUE THREAD

**Issue by bbycnzj** [ObjSal/p7zip#1]

**Comment by ObjSal** [comment]
If I understand correctly, you are asking for a library for iOS, then I recommend a project called "Objective-Zip"

**Comment by bbycnzj** [comment]
Thank you very much！
I want a 7z  source code that supports compression for a password in iOS.
Can you help me?

At 2015-06-08 11:43:10, "Salvador Guerrero" notifications@github.com wrote:

If I understand correctly, you are asking for a library for iOS, then I recommend a project called "Objective-Zip"

**Comment by ObjSal** [comment]
Objective-Zip supports compression with password, I think this is the closest open-source project you can get, here are 2 links:

• https://github.com/gianlucabertani/Objective-Zip
• https://github.com/AgileBits/objective-zip

I hope it works!

**Comment by bbycnzj** [comment]
Thank your very much！ Good luck！

At 2015-06-08 12:07:14, "Salvador Guerrero" notifications@github.com wrote:

Objective-Zip supports compression with password, I think this is the closest open-source project you can get, here are 2 links:

• https://github.com/gianlucabertani/Objective-Zip
• https://github.com/AgileBits/objective-zip

I hope it works!
